service: api-lab
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev # Set the default stage used. Default is dev
  region: us-east-1
  memorySize: 512
functions:
   api:
    handler: lambda.handler
    events: 
      - http: ANY {proxy+}
